#! /bin/sh
### BEGIN INIT INFO
# Provides: OSSEC HIDS
# Required-Start: $network $remote_fs $syslog $time
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: OSSEC HIDS
### END INIT INFO
# /etc/init.d/webcam
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting webcam script"
    export LD_LIBRARY_PATH="/home/pi/mjpg_streamer/mjpg_streamer"
    /home/pi/mjpg_streamer/mjpg_streamer -i "input_uvc.so -r 640x480 -f 20 -n" -o "output_http.so -p 8080 -w /home/pi/mjpg_streamer/www" &
    ;;
  stop)
    echo "Stopping webcam script"
    killall mjpg_streamer
    ;;
  *)
    echo "Usage: /etc/init.d/webcam {start|stop}"
    exit 1
    ;;
esac
exit 0
